### PR TITLE
- add setYear,setMonth,setDay,...

### PR DESCRIPTION
**Pull request by uzi18**
Ability to chandge date/time in RtcDateTime

### CODE REVIEW

**Comment by Makuna** [comment]
The original intent was that this structure contains constant values, if you want to set one one, you create one not modify it.  This model allows for the compiler to create more optimized code. 
Why do you need to have these setter methods?

**Comment by uzi18** [comment]
If You need only to adjust time or date, You can try this:
               RtcDateTime rtc_now = Rtc.GetDateTime();
                rtc_now.setHour(10);
                rtc_now.setMinute(11);
                rtc_now.setSecond(12);
                Rtc.SetDateTime(rtc_now);

Isn't it more optimized, then construct another object with part of old
data?


2017-07-24 17:45 GMT+02:00 Michael Miller <notifications@github.com>:

**Comment by Makuna** [comment]
But what REAL scenario do you have?  The example you give isn't a real scenario.  
Why would you get the time and then adjust it to a specific date/time?  

You might get the time, and compare to another time to see if its out of date (like getting the time from a NTP server); but then you would just use the accurate time to set.

Their are scenarios where you adjust the datetime, but then you usually work only in differences of seconds, and it supports this
```
rtc_now += 5; // due to some error, I know the rtc_now is five seconds slow, adjust it.
```

**Comment by uzi18** [comment]
This is real scenario, user send setDate or setTime by Serial and AVR must adjust this like shown before.

I don\t understand why I can add seconds to rtc_now and can't set it directly.
can pass unixtime into new object and receive hour,minute or day of week,
but cant change only day and check what is a day of week.
Someone could use RtcDateTime class alone to calculate unixtime.
On other hand gcc will cut out these methods if not used.

I will keep it in my fork, as I need it.

**Comment by Makuna** [comment]
NOTE:  When constructing an object the compiler can take shortcuts that it can't assume by property setters.  This is why this model is used and enforced.  Did you try it without your changes and compare the size/memory footprint of the code?

So the issue you are raising is that your Serial API allows setting the time separate from setting the date thus making this an issue for you.  Did you have a reason for keeping them separate APIs?

**Comment by fungreenfox** [comment]
exit status 1
'RtcDateTime' does not name a type

**Comment by uzi18** [comment]
I'm keeping one RtcDateTime object in memory all the time,  to have access to time during runtime.

**Comment by id1402** [comment]
Please say how to set date and time?
For example: Apr 25 2023, 00:28:09
How to set this date and time?
I have seen examples/DS1302_Simple. It doesn't help.
```
RtcDateTime compiled = RtcDateTime(__DATE__, __TIME__);
Rtc.SetDateTime(compiled);
```
No other example using SetDateTime. But nobody wants to set date and time to __DATE__, __TIME__ in real scenario.
Please help.

**Comment by Makuna** [comment]
> Apr 25 2023, 00:28:09

It is bad form to ask questions on anything other than the code in a pull request.  See [Discussion started for you](https://github.com/Makuna/Rtc/discussions/169)

**Pull request closed without merging**
